// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHkwNbVIUIdxgQTdDiInpSGGJvp8RfuTI',
    appId: '1:992564397210:web:8c05443c4d556c96568b23',
    messagingSenderId: '992564397210',
    projectId: 'finanso-459e8',
    authDomain: 'finanso-459e8.firebaseapp.com',
    storageBucket: 'finanso-459e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj1rquzRS2ktmCHTaG6_lRzEuF2bnp3Gs',
    appId: '1:992564397210:android:53e16b68da67c72f568b23',
    messagingSenderId: '992564397210',
    projectId: 'finanso-459e8',
    storageBucket: 'finanso-459e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQSCvbvglpEdF68wfyOsa2CaKRXui8QGQ',
    appId: '1:992564397210:ios:eaf126c576829395568b23',
    messagingSenderId: '992564397210',
    projectId: 'finanso-459e8',
    storageBucket: 'finanso-459e8.appspot.com',
    iosBundleId: 'com.example.stockMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQSCvbvglpEdF68wfyOsa2CaKRXui8QGQ',
    appId: '1:992564397210:ios:eaf126c576829395568b23',
    messagingSenderId: '992564397210',
    projectId: 'finanso-459e8',
    storageBucket: 'finanso-459e8.appspot.com',
    iosBundleId: 'com.example.stockMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHkwNbVIUIdxgQTdDiInpSGGJvp8RfuTI',
    appId: '1:992564397210:web:f00a9ae2b00ff4f3568b23',
    messagingSenderId: '992564397210',
    projectId: 'finanso-459e8',
    authDomain: 'finanso-459e8.firebaseapp.com',
    storageBucket: 'finanso-459e8.appspot.com',
  );

}